### ISSUE TITLE
More versions

### ISSUE THREAD

**Issue by larsbrinkhoff** [larsbrinkhoff/docker-emacsen#3]
Emacs 24.3 and 24.4 has been mentioned.

**Comment by larsbrinkhoff** [comment]
Also 24.2 @syohex

**Comment by syohex** [comment]
Thanks for good product.

Sorry I don't need 24.2. I referred it because I wonder why you can build such old Emacs. I cannot succeed even `./configure` on newer Linux environment(Ubuntu 16.04 etc).

I'm sorry to confuse you.

**Comment by larsbrinkhoff** [comment]
Right, the build procedure has changed a bit over the years.  The `bootstrap.sh` script takes care of running `configure`.

My Docker image builds on top of `ubuntu:latest`, which should be Ubuntu 16.04.

**Comment by larsbrinkhoff** [comment]
Fixed in 460af07b52dfcd146eb73417a6bc72c4b3521723.  There is currently only room for one more Emacs version, due to a 50-minute build limit imposed by Travis CI.  I somewhat randomly picked 24.3.
